---

- hosts: localhost
  gather_facts: yes
  tags: always
  tasks:
    - name: create timestamp file
      lineinfile:
        line: "started {{ ansible_date_time.iso8601_micro }}"
        dest: "/tmp/ansible.timestamp"
        create: yes
      changed_when: false
      tags: environment_status_reporting
    - name: Update apt-cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

#- hosts: localhost
  #roles:
    #- { role: common, tags: common }
    #- { role: consul, tags: consul }

#- hosts: mysql
  #roles:
    #- { role: mysql }

#- hosts: postgresql
  #roles:
    #- { role: postgresql }

- hosts: localhost
  tasks:
    - name: create timestamp file
      lineinfile:
        line: "completed {{ ansible_date_time.iso8601_micro }}"
        dest: "/tmp/ansible.timestamp"
        create: yes
      changed_when: false
      tags: environment_status_reporting
